const ukRegions = [
  "Aberdeen City",
  "Aberdeenshire",
  "Angus",
  "Antrim and Newtownabbey",
  "Ards and North Down",
  "Argyll and Bute",
  "Armagh City, Banbridge and Craigavon",
  "Barking and Dagenham",
  "Barnet",
  "Barnsley",
  "Bath and North East Somerset",
  "Bedford",
  "Belfast City",
  "Berkshire",
  "Bexley",
  "Birmingham",
  "Blackburn with Darwen",
  "Blackpool",
  "Blaenau Gwent",
  "Bolton",
  "Bournemouth, Christchurch and Poole",
  "Bracknell Forest",
  "Bradford",
  "Brent",
  "Bridgend",
  "Brighton and Hove",
  "Bristol, City of",
  "Bromley",
  "Buckinghamshire",
  "Bury",
  "Caerphilly",
  "Calderdale",
  "Cambridgeshire",
  "Camden",
  "Cardiff",
  "Carmarthenshire",
  "Causeway Coast and Glens",
  "Central Bedfordshire",
  "Ceredigion",
  "Cheshire East",
  "Cheshire West and Chester",
  "Clackmannanshire",
  "Conwy",
  "Cornwall",
  "Coventry",
  "Croydon",
  "Cumbria",
  "Darlington",
  "Denbighshire",
  "Derby",
  "Derbyshire",
  "Derry and Strabane",
  "Devon",
  "Doncaster",
  "Dorset",
  "Dudley",
  "Dumfries and Galloway",
  "Dundee City",
  "Durham, County",
  "Ealing",
  "East Ayrshire",
  "East Dunbartonshire",
  "East Lothian",
  "East Renfrewshire",
  "East Riding of Yorkshire",
  "East Sussex",
  "Edinburgh, City of",
  "Eilean Siar",
  "Enfield",
  "Essex",
  "Falkirk",
  "Fermanagh and Omagh",
  "Fife",
  "Flintshire",
  "Gateshead",
  "Glasgow City",
  "Gloucestershire",
  "Greenwich",
  "Gwynedd",
  "Hackney",
  "Halton",
  "Hammersmith and Fulham",
  "Hampshire",
  "Haringey",
  "Harrow",
  "Hartlepool",
  "Havering",
  "Herefordshire",
  "Hertfordshire",
  "Highland",
  "Hillingdon",
  "Hounslow",
  "Inverclyde",
  "Isle of Anglesey",
  "Isle of Wight",
  "Isles of Scilly",
  "Islington",
  "Kensington and Chelsea",
  "Kent",
  "Kingston upon Hull",
  "Kingston upon Thames",
  "Kirklees",
  "Knowsley",
  "Lambeth",
  "Lancashire",
  "Leeds",
  "Leicester",
  "Leicestershire",
  "Lewisham",
  "Lincolnshire",
  "Lisburn and Castlereagh",
  "Liverpool",
  "London, City of",
  "Luton",
  "Manchester",
  "Medway",
  "Merthyr Tydfil",
  "Merton",
  "Mid and East Antrim",
  "Mid-Ulster",
  "Middlesbrough",
  "Midlothian",
  "Milton Keynes",
  "Monmouthshire",
  "Moray",
  "Neath Port Talbot",
  "Newcastle upon Tyne",
  "Newham",
  "Newport",
  "Newry, Mourne and Down",
  "Norfolk",
  "North Ayrshire",
  "North East Lincolnshire",
  "North Lanarkshire",
  "North Lincolnshire",
  "North Somerset",
  "North Tyneside",
  "North Yorkshire",
  "Northamptonshire",
  "Northumberland",
  "Nottingham",
  "Nottinghamshire",
  "Oldham",
  "Orkney Islands",
  "Oxfordshire",
  "Pembrokeshire",
  "Perth and Kinross",
  "Peterborough",
  "Plymouth",
  "Portsmouth",
  "Powys",
  "Reading",
  "Redbridge",
  "Redcar and Cleveland",
  "Renfrewshire",
  "Rhondda Cynon Taff",
  "Richmond upon Thames",
  "Rochdale",
  "Rotherham",
  "Rutland",
  "Salford",
  "Sandwell",
  "Scottish Borders",
  "Sefton",
  "Sheffield",
  "Shetland Islands",
  "Shropshire",
  "Slough",
  "Solihull",
  "Somerset",
  "South Ayrshire",
  "South Gloucestershire",
  "South Lanarkshire",
  "South Tyneside",
  "Southampton",
  "Southend-on-Sea",
  "Southwark",
  "St. Helens",
  "Staffordshire",
  "Stirling",
  "Stockport",
  "Stockton-on-Tees",
  "Stoke-on-Trent",
  "Suffolk",
  "Sunderland",
  "Surrey",
  "Sutton",
  "Swansea",
  "Swindon",
  "Tameside",
  "Telford and Wrekin",
  "Thurrock",
  "Torbay",
  "Torfaen",
  "Tower Hamlets",
  "Trafford",
  "Vale of Glamorgan, The",
  "Wakefield",
  "Walsall",
  "Waltham Forest",
  "Wandsworth",
  "Warrington",
  "Warwickshire",
  "West Berkshire",
  "West Dunbartonshire",
  "West Lothian",
  "West Sussex",
  "Westminster",
  "Wigan",
  "Wiltshire",
  "Windsor and Maidenhead",
  "Wirral",
  "Wokingham",
  "Wolverhampton",
  "Worcestershire",
  "Wrexham",
  "York",
];

export default ukRegions;
