name: Deploy to IBM Cloud Code Engine

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
       # Install IBM Cloud CLI
      - name: Install IBM Cloud CLI
        run: |
          curl -sL https://ibm.biz/idt-installer | bash
          ibmcloud config --check-version=false
        
      # # Log in to IBM Cloud
      # - name: Log in to IBM Cloud
      #   run: |
      #     ibmcloud login --apikey FeVmuUG9frh7_S_yzXqQ-6lFrQSdhlfNndWeI5m2TYIU
      #     ibmcloud target -r eu-gb -g 2022-VetDB

      # Authenticate with IBM Cloud CLI
      - name: Authenticate with IBM Cloud CLI
        run: |
          ibmcloud login --apikey "FeVmuUG9frh7_S_yzXqQ-6lFrQSdhlfNndWeI5m2TYIU" -r "eu-gb" -g "2022-VetDB"
          ibmcloud cr region-set "eu-gb"
          ibmcloud cr login

       # Log in to IBM Cloud Container Registry
      - name: Log in to IBM Cloud Container Registry
        run: |
          ibmcloud cr login
          ibmcloud cr region-set "eu-gb"

        
      # Build frontend and backend Docker images
      - name: Build frontend Docker image
        run: |
          docker build --platform linux/amd64 -t vetdb-frontend:${{ github.sha }} ./frontend
        shell: bash
        
      - name: Build backend Docker image
        run: |
          docker build --platform linux/amd64 -t vetdb-backend:${{ github.sha }} ./backend
        shell: bash

      
      # Tag frontend and backend Docker images
      - name: Tag frontend Docker image
        run: |
          docker tag vetdb-frontend:${{ github.sha }} uk.icr.io/2022-vetdb/vetdb-frontend:${{ github.sha }}
        shell: bash
        
      - name: Tag backend Docker image
        run: |
          docker tag vetdb-backend:${{ github.sha }} uk.icr.io/2022-vetdb/vetdb-backend:${{ github.sha }}
        shell: bash
      
      # Push frontend and backend Docker images to container registry
      - name: Push frontend Docker image
        run: |
          docker push uk.icr.io/2022-vetdb/vetdb-frontend:${{ github.sha }}
        shell: bash
        
      - name: Push backend Docker image
        run: |
          docker push uk.icr.io/2022-vetdb/vetdb-backend:${{ github.sha }}
        shell: bash
      
      # Deploy frontend and backend to IBM Cloud Code Engine
      - name: Deploy frontend to IBM Cloud Code Engine
        run: |
          ibmcloud login --apikey FeVmuUG9frh7_S_yzXqQ-6lFrQSdhlfNndWeI5m2TYIU
          ibmcloud target -r eu-gb -g 2022-VetDB
          ibmcloud ce project select -n VetDB
          ibmcloud ce app create vetdb-frontend --image uk.icr.io/2022-vetdb/vetdb-frontend:${{ github.sha }} --min-scale 0 --max-scale 10 --memory 32Gi --cpu 4 --ephemeral-storage 8Gi --registry-secret-name frontend-container-registry
          
      - name: Deploy backend to IBM Cloud Code Engine
        run: |
          ibmcloud login --apikey FeVmuUG9frh7_S_yzXqQ-6lFrQSdhlfNndWeI5m2TYIU
          ibmcloud target -r eu-gb -g 2022-VetDB
          ibmcloud ce project select -n VetDB
          ibmcloud ce app create vetdb-backend --image uk.icr.io/2022-vetdb/vetdb-backend:${{ github.sha }} --min-scale 0 --max-scale 10 --memory 32Gi --cpu 4 --ephemeral-storage 8Gi --registry-secret-name frontend-container-registry
